Shell: add bash configuration

diff --git a/scripts/generate_aliases_or_variables_file b/scripts/generate_aliases_or_variables_file
--- a/scripts/generate_aliases_or_variables_file
+++ b/scripts/generate_aliases_or_variables_file
@@ -3,10 +3,27 @@
 ################################################################################
 # Parse arguments
 ################################################################################
+error() {
+    echo "$1" >&2
+    exit 1
+}
+
+assert_value_one_of() {
+    local Name=$1; shift
+    local Value=$1; shift
+    for Valid in "$@"; do
+        [[ "$Value" == "$Valid" ]] && return
+    done
+    error "$Name must be one of: $*, got '$Value'"
+}
+
 AliasesOrVariables=$1
-Shell="${2,,}" # Tranform to lower case.
+Shell=$2
 InputFile=$3
 OutputFile=$4
+
+assert_value_one_of AliasesOrVariables "$AliasesOrVariables" aliases variables
+assert_value_one_of Shell "$Shell" zsh bash tcsh
 
 ################################################################################
 # Do nothing if checksum hasn't changed
@@ -63,35 +80,53 @@ extract_section() {
     >> "$OutputFile"
 }
 
+## - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+## Aliases
+## - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 if [[ $AliasesOrVariables == aliases ]]; then
     extract_section "Aliases common for all shells"
-    if [[ $Shell == zsh ]]; then
+
+    if [[ $Shell == zsh || $Shell == bash ]]; then
         sed -i 's/{separator}/=/g' "$OutputFile"
-        extract_section "Aliases specific to ZSH"
+        extract_section "Aliases for POSIX shells"
+        [[ $Shell == zsh ]]  && extract_section "Aliases specific to zsh"
+        [[ $Shell == bash ]] && extract_section "Aliases specific to bash"
     fi
+
     if [[ $Shell == tcsh ]]; then
         sed -i 's/{separator}/ /g' "$OutputFile"
-        extract_section "Aliases specific to TCSH"
+        extract_section "Aliases specific to tcsh"
     fi
 fi
 
+## - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+## Variables
+## - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 if [[ $AliasesOrVariables == variables ]]; then
     extract_section "Variables common for all shells"
-    if [[ $Shell == zsh ]]; then
+
+    if [[ $Shell == zsh || $Shell == bash ]]; then
         sed -i -e 's/{env_var}/export/g' \
                -e 's/{separator}/=/g'    \
                -e 's/{shell_var}//g'     \
                "$OutputFile"
-        extract_section "Variables specific to ZSH"
+        extract_section "Variables for POSIX shells"
+        [[ $Shell == zsh ]]  && extract_section "Variables specific to zsh"
+        [[ $Shell == bash ]] && extract_section "Variables specific to bash"
     fi
+
     if [[ $Shell == tcsh ]]; then
         sed -i -e 's/{env_var}/setenv/g' "$OutputFile" \
                -e 's/{separator}/ /g'                    \
                -e 's/{shell_var}/set /g'                 \
                "$OutputFile"
-        extract_section "Variables specific to TCSH"
+        extract_section "Variables specific to tcsh"
     fi
+
     extract_section "Unset variables"
 fi
 
+################################################################################
+# Cleanup
+################################################################################
 rm "$LockFile"
